import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const HomeConatiner = styled.main``

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomeConatiner></HomeConatiner>
    </>
  )
}

export default Home
